name: SmartCV
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - autopep8=1.5.7
  - flake8=3.9.2
  - jedi=0.18.0
  - jupyter=1.0.0
  - pandas=1.3.3
  - pip
  - pylint=2.9.6
  - tqdm
  - seaborn=0.11.2
  - nltk
  - PyPDF2
  - pydrive2=1.10.0=pyhd8ed1ab_1
  - tensorflow==2.4.1
  - pip:
    - black==21.9b0
    - plotnine==0.8.0
    - pdfplumber==0.6.0
    - python-docx==0.8.11
    - Unidecode==1.3.2
    - contractions==0.1.66
    - pyspellchecker==0.6.3
    - scikit-learn==0.23.2
    - langdetect==1.0.9
